#############################################################################
# Makefile for building: BankingSystemGUI.app/Contents/MacOS/BankingSystemGUI
# Generated by qmake (3.1) (Qt 6.9.1)
# Project:  BankingSystem.pro
# Template: app
# Command: /Users/amirmahdinaghsh/Qt/6.9.1/macos/bin/qmake -o Makefile BankingSystem.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12 -Wall -Wextra $(DEFINES)
INCPATH       = -I. -I../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers -I../../../Qt/6.9.1/macos/lib/QtGui.framework/Headers -I../../../Qt/6.9.1/macos/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../Qt/6.9.1/macos/mkspecs/macx-clang -F/Users/amirmahdinaghsh/Qt/6.9.1/macos/lib
QMAKE         = /Users/amirmahdinaghsh/Qt/6.9.1/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/amirmahdinaghsh/Qt/6.9.1/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/amirmahdinaghsh/Qt/6.9.1/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = BankingSystemGUI1.0.0
DISTDIR = /Users/amirmahdinaghsh/Documents/GitHub/Bank_Operation/.tmp/BankingSystemGUI1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/amirmahdinaghsh/Qt/6.9.1/macos/lib
LIBS          = $(SUBLIBS) -F/Users/amirmahdinaghsh/Qt/6.9.1/macos/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework IOKit -framework DiskArbitration -framework UniformTypeIdentifiers -framework AGL -framework OpenGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main_qt.cpp \
		bankingsystem.cpp \
		loginwindow.cpp \
		customerwindow.cpp \
		adminwindow.cpp \
		transferdialog.cpp \
		Account.cpp \
		User.cpp \
		Customer.cpp \
		Admin.cpp \
		SavingsAccount.cpp \
		CurrentAccount.cpp \
		LoanAccount.cpp moc_bankingsystem.cpp \
		moc_loginwindow.cpp \
		moc_customerwindow.cpp \
		moc_adminwindow.cpp \
		moc_transferdialog.cpp
OBJECTS       = main_qt.o \
		bankingsystem.o \
		loginwindow.o \
		customerwindow.o \
		adminwindow.o \
		transferdialog.o \
		Account.o \
		User.o \
		Customer.o \
		Admin.o \
		SavingsAccount.o \
		CurrentAccount.o \
		LoanAccount.o \
		moc_bankingsystem.o \
		moc_loginwindow.o \
		moc_customerwindow.o \
		moc_adminwindow.o \
		moc_transferdialog.o
DIST          = ../../../Qt/6.9.1/macos/mkspecs/features/spec_pre.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/device_config.prf \
		../../../Qt/6.9.1/macos/mkspecs/common/unix.conf \
		../../../Qt/6.9.1/macos/mkspecs/common/mac.conf \
		../../../Qt/6.9.1/macos/mkspecs/common/macx.conf \
		../../../Qt/6.9.1/macos/mkspecs/common/sanitize.conf \
		../../../Qt/6.9.1/macos/mkspecs/common/gcc-base.conf \
		../../../Qt/6.9.1/macos/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/6.9.1/macos/mkspecs/common/clang.conf \
		../../../Qt/6.9.1/macos/mkspecs/common/clang-mac.conf \
		../../../Qt/6.9.1/macos/mkspecs/qconfig.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_ext_freetype.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_ext_libpng.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_ext_openxr_loader.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_ffmpegmediapluginimpl_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsplatform.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsplatform_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_linguist.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_png_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlformat_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlls_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlmeta.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlnetwork.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3d.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3deffects.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dxr.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dxr_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickeffects.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickvectorimage.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_shadertools.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_spatialaudio.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_testinternals_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../../../Qt/6.9.1/macos/mkspecs/features/qt_functions.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/qt_config.prf \
		../../../Qt/6.9.1/macos/mkspecs/macx-clang/qmake.conf \
		../../../Qt/6.9.1/macos/mkspecs/features/spec_post.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/exclusive_builds.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/mac/sdk.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/toolchain.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/mac/toolchain.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/default_pre.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/mac/default_pre.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/resolve_config.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/default_post.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/mac/default_post.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/mac/objective_c.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/mac/mac.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/warn_on.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/permissions.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/qt.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/resources_functions.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/resources.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/moc.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/unix/opengl.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/uic.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/unix/thread.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/qmake_use.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/file_copies.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/mac/rez.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/testcase_targets.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/exceptions.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/yacc.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/lex.prf \
		BankingSystem.pro bankingsystem.h \
		loginwindow.h \
		customerwindow.h \
		adminwindow.h \
		transferdialog.h \
		Account.h \
		User.h \
		Customer.h \
		Admin.h \
		SavingsAccount.h \
		CurrentAccount.h \
		LoanAccount.h \
		LinkedList.h main_qt.cpp \
		bankingsystem.cpp \
		loginwindow.cpp \
		customerwindow.cpp \
		adminwindow.cpp \
		transferdialog.cpp \
		Account.cpp \
		User.cpp \
		Customer.cpp \
		Admin.cpp \
		SavingsAccount.cpp \
		CurrentAccount.cpp \
		LoanAccount.cpp
QMAKE_TARGET  = BankingSystemGUI
DESTDIR       = 
TARGET        = BankingSystemGUI.app/Contents/MacOS/BankingSystemGUI

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 15.5
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT__QMAKE_STASH_ = 
EXPORT_VALID_ARCHS = x86_64 arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/amirmahdinaghsh/Documents/GitHub/Bank_Operation/BankingSystem.pro


include /Users/amirmahdinaghsh/Qt/6.9.1/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

BankingSystemGUI.app/Contents/MacOS/BankingSystemGUI: ui_loginwindow.h ui_customerwindow.h $(OBJECTS)  
	@test -d BankingSystemGUI.app/Contents/MacOS/ || mkdir -p BankingSystemGUI.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: BankingSystem.pro ../../../Qt/6.9.1/macos/mkspecs/macx-clang/qmake.conf ../../../Qt/6.9.1/macos/mkspecs/features/spec_pre.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/device_config.prf \
		../../../Qt/6.9.1/macos/mkspecs/common/unix.conf \
		../../../Qt/6.9.1/macos/mkspecs/common/mac.conf \
		../../../Qt/6.9.1/macos/mkspecs/common/macx.conf \
		../../../Qt/6.9.1/macos/mkspecs/common/sanitize.conf \
		../../../Qt/6.9.1/macos/mkspecs/common/gcc-base.conf \
		../../../Qt/6.9.1/macos/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/6.9.1/macos/mkspecs/common/clang.conf \
		../../../Qt/6.9.1/macos/mkspecs/common/clang-mac.conf \
		../../../Qt/6.9.1/macos/mkspecs/qconfig.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_ext_freetype.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_ext_libpng.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_ext_openxr_loader.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_ffmpegmediapluginimpl_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsplatform.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsplatform_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_linguist.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_png_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlformat_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlls_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlmeta.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlnetwork.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3d.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3deffects.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dxr.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dxr_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickeffects.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickvectorimage.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_shadertools.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_spatialaudio.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_testinternals_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../../../Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../../../Qt/6.9.1/macos/mkspecs/features/qt_functions.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/qt_config.prf \
		../../../Qt/6.9.1/macos/mkspecs/macx-clang/qmake.conf \
		../../../Qt/6.9.1/macos/mkspecs/features/spec_post.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/exclusive_builds.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/mac/sdk.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/toolchain.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/mac/toolchain.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/default_pre.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/mac/default_pre.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/resolve_config.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/default_post.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/mac/default_post.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/mac/objective_c.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/mac/mac.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/warn_on.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/permissions.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/qt.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/resources_functions.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/resources.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/moc.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/unix/opengl.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/uic.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/unix/thread.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/qmake_use.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/file_copies.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/mac/rez.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/testcase_targets.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/exceptions.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/yacc.prf \
		../../../Qt/6.9.1/macos/mkspecs/features/lex.prf \
		BankingSystem.pro \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../../../Qt/6.9.1/macos/lib/QtGui.framework/Resources/QtGui.prl \
		../../../Qt/6.9.1/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile BankingSystem.pro
../../../Qt/6.9.1/macos/mkspecs/features/spec_pre.prf:
../../../Qt/6.9.1/macos/mkspecs/features/device_config.prf:
../../../Qt/6.9.1/macos/mkspecs/common/unix.conf:
../../../Qt/6.9.1/macos/mkspecs/common/mac.conf:
../../../Qt/6.9.1/macos/mkspecs/common/macx.conf:
../../../Qt/6.9.1/macos/mkspecs/common/sanitize.conf:
../../../Qt/6.9.1/macos/mkspecs/common/gcc-base.conf:
../../../Qt/6.9.1/macos/mkspecs/common/gcc-base-mac.conf:
../../../Qt/6.9.1/macos/mkspecs/common/clang.conf:
../../../Qt/6.9.1/macos/mkspecs/common/clang-mac.conf:
../../../Qt/6.9.1/macos/mkspecs/qconfig.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_ext_freetype.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_ext_libjpeg.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_ext_libpng.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_ext_openxr_loader.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_charts.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_charts_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_chartsqml.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_chartsqml_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_core.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_example_icons_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_ffmpegmediapluginimpl_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_freetype_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_help.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_jpeg_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsanimation.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsplatform.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsplatform_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labssettings.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_linguist.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_network.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_png_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlassetdownloader.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlcompiler.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlcore.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlformat_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlintegration.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlls_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlmeta.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlmeta_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlnetwork.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3d.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3d_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3deffects.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dparticles.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dutils.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dxr.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dxr_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickeffects.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickeffects_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktimeline.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickvectorimage.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickvectorimage_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_shadertools.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_shadertools_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_spatialaudio.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_testinternals_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_tools_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
../../../Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
../../../Qt/6.9.1/macos/mkspecs/features/qt_functions.prf:
../../../Qt/6.9.1/macos/mkspecs/features/qt_config.prf:
../../../Qt/6.9.1/macos/mkspecs/macx-clang/qmake.conf:
../../../Qt/6.9.1/macos/mkspecs/features/spec_post.prf:
../../../Qt/6.9.1/macos/mkspecs/features/exclusive_builds.prf:
../../../Qt/6.9.1/macos/mkspecs/features/mac/sdk.prf:
../../../Qt/6.9.1/macos/mkspecs/features/toolchain.prf:
../../../Qt/6.9.1/macos/mkspecs/features/mac/toolchain.prf:
../../../Qt/6.9.1/macos/mkspecs/features/default_pre.prf:
../../../Qt/6.9.1/macos/mkspecs/features/mac/default_pre.prf:
../../../Qt/6.9.1/macos/mkspecs/features/resolve_config.prf:
../../../Qt/6.9.1/macos/mkspecs/features/default_post.prf:
../../../Qt/6.9.1/macos/mkspecs/features/mac/default_post.prf:
../../../Qt/6.9.1/macos/mkspecs/features/mac/objective_c.prf:
../../../Qt/6.9.1/macos/mkspecs/features/mac/mac.prf:
../../../Qt/6.9.1/macos/mkspecs/features/warn_on.prf:
../../../Qt/6.9.1/macos/mkspecs/features/permissions.prf:
../../../Qt/6.9.1/macos/mkspecs/features/qt.prf:
../../../Qt/6.9.1/macos/mkspecs/features/resources_functions.prf:
../../../Qt/6.9.1/macos/mkspecs/features/resources.prf:
../../../Qt/6.9.1/macos/mkspecs/features/moc.prf:
../../../Qt/6.9.1/macos/mkspecs/features/unix/opengl.prf:
../../../Qt/6.9.1/macos/mkspecs/features/uic.prf:
../../../Qt/6.9.1/macos/mkspecs/features/unix/thread.prf:
../../../Qt/6.9.1/macos/mkspecs/features/qmake_use.prf:
../../../Qt/6.9.1/macos/mkspecs/features/file_copies.prf:
../../../Qt/6.9.1/macos/mkspecs/features/mac/rez.prf:
../../../Qt/6.9.1/macos/mkspecs/features/mac/asset_catalogs.prf:
../../../Qt/6.9.1/macos/mkspecs/features/testcase_targets.prf:
../../../Qt/6.9.1/macos/mkspecs/features/exceptions.prf:
../../../Qt/6.9.1/macos/mkspecs/features/yacc.prf:
../../../Qt/6.9.1/macos/mkspecs/features/lex.prf:
BankingSystem.pro:
../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../../../Qt/6.9.1/macos/lib/QtGui.framework/Resources/QtGui.prl:
../../../Qt/6.9.1/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile BankingSystem.pro

qmake_all: FORCE

BankingSystemGUI.app/Contents/PkgInfo: 
	@test -d BankingSystemGUI.app/Contents || mkdir -p BankingSystemGUI.app/Contents
	@$(DEL_FILE) BankingSystemGUI.app/Contents/PkgInfo
	@echo "APPL????" > BankingSystemGUI.app/Contents/PkgInfo
BankingSystemGUI.app/Contents/Info.plist: 
	@test -d BankingSystemGUI.app/Contents || mkdir -p BankingSystemGUI.app/Contents
	@$(DEL_FILE) BankingSystemGUI.app/Contents/Info.plist
	@plutil -convert xml1 -o - ../../../Qt/6.9.1/macos/mkspecs/macx-clang/Info.plist.app | sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.BankingSystemGUI,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.BankingSystemGUI,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,BankingSystemGUI,g" -e "s,@LIBRARY@,BankingSystemGUI,g" -e "s,\$${EXECUTABLE_NAME},BankingSystemGUI,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" >BankingSystemGUI.app/Contents/Info.plist

all: Makefile \
		BankingSystemGUI.app/Contents/PkgInfo \
		BankingSystemGUI.app/Contents/Info.plist BankingSystemGUI.app/Contents/MacOS/BankingSystemGUI

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents bankingsystem.h loginwindow.h customerwindow.h adminwindow.h transferdialog.h Account.h User.h Customer.h Admin.h SavingsAccount.h CurrentAccount.h LoanAccount.h LinkedList.h $(DISTDIR)/
	$(COPY_FILE) --parents main_qt.cpp bankingsystem.cpp loginwindow.cpp customerwindow.cpp adminwindow.cpp transferdialog.cpp Account.cpp User.cpp Customer.cpp Admin.cpp SavingsAccount.cpp CurrentAccount.cpp LoanAccount.cpp $(DISTDIR)/
	$(COPY_FILE) --parents loginwindow.ui customerwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r BankingSystemGUI.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_bankingsystem.cpp moc_loginwindow.cpp moc_customerwindow.cpp moc_adminwindow.cpp moc_transferdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_bankingsystem.cpp moc_loginwindow.cpp moc_customerwindow.cpp moc_adminwindow.cpp moc_transferdialog.cpp
moc_bankingsystem.cpp: bankingsystem.h \
		LinkedList.h \
		Customer.h \
		User.h \
		Admin.h \
		Account.h \
		../../../Qt/6.9.1/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.1/macos/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/6.9.1/macos/libexec/moc
	/Users/amirmahdinaghsh/Qt/6.9.1/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=201402L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=17 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/amirmahdinaghsh/Qt/6.9.1/macos/mkspecs/macx-clang -I/Users/amirmahdinaghsh/Documents/GitHub/Bank_Operation -I/Users/amirmahdinaghsh/Qt/6.9.1/macos/lib/QtWidgets.framework/Headers -I/Users/amirmahdinaghsh/Qt/6.9.1/macos/lib/QtGui.framework/Headers -I/Users/amirmahdinaghsh/Qt/6.9.1/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/17/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/amirmahdinaghsh/Qt/6.9.1/macos/lib bankingsystem.h -o moc_bankingsystem.cpp

moc_loginwindow.cpp: loginwindow.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qmessagebox.h \
		Customer.h \
		User.h \
		LinkedList.h \
		Admin.h \
		../../../Qt/6.9.1/macos/libexec/moc
	/Users/amirmahdinaghsh/Qt/6.9.1/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=201402L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=17 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/amirmahdinaghsh/Qt/6.9.1/macos/mkspecs/macx-clang -I/Users/amirmahdinaghsh/Documents/GitHub/Bank_Operation -I/Users/amirmahdinaghsh/Qt/6.9.1/macos/lib/QtWidgets.framework/Headers -I/Users/amirmahdinaghsh/Qt/6.9.1/macos/lib/QtGui.framework/Headers -I/Users/amirmahdinaghsh/Qt/6.9.1/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/17/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/amirmahdinaghsh/Qt/6.9.1/macos/lib loginwindow.h -o moc_loginwindow.cpp

moc_customerwindow.cpp: customerwindow.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QListWidgetItem \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qlistwidget.h \
		Customer.h \
		User.h \
		LinkedList.h \
		../../../Qt/6.9.1/macos/libexec/moc
	/Users/amirmahdinaghsh/Qt/6.9.1/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=201402L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=17 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/amirmahdinaghsh/Qt/6.9.1/macos/mkspecs/macx-clang -I/Users/amirmahdinaghsh/Documents/GitHub/Bank_Operation -I/Users/amirmahdinaghsh/Qt/6.9.1/macos/lib/QtWidgets.framework/Headers -I/Users/amirmahdinaghsh/Qt/6.9.1/macos/lib/QtGui.framework/Headers -I/Users/amirmahdinaghsh/Qt/6.9.1/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/17/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/amirmahdinaghsh/Qt/6.9.1/macos/lib customerwindow.h -o moc_customerwindow.cpp

moc_adminwindow.cpp: adminwindow.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QGridLayout \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QLineEdit \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QTextEdit \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QTableWidget \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QTableWidgetItem \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QComboBox \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QGroupBox \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qgroupbox.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QTabWidget \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QInputDialog \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QHeaderView \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qheaderview.h \
		Admin.h \
		User.h \
		LinkedList.h \
		bankingsystem.h \
		Customer.h \
		Account.h \
		../../../Qt/6.9.1/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.1/macos/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/6.9.1/macos/libexec/moc
	/Users/amirmahdinaghsh/Qt/6.9.1/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=201402L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=17 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/amirmahdinaghsh/Qt/6.9.1/macos/mkspecs/macx-clang -I/Users/amirmahdinaghsh/Documents/GitHub/Bank_Operation -I/Users/amirmahdinaghsh/Qt/6.9.1/macos/lib/QtWidgets.framework/Headers -I/Users/amirmahdinaghsh/Qt/6.9.1/macos/lib/QtGui.framework/Headers -I/Users/amirmahdinaghsh/Qt/6.9.1/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/17/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/amirmahdinaghsh/Qt/6.9.1/macos/lib adminwindow.h -o moc_adminwindow.cpp

moc_transferdialog.cpp: transferdialog.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qdialog.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QGridLayout \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QComboBox \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QLineEdit \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qmessagebox.h \
		Customer.h \
		User.h \
		LinkedList.h \
		Account.h \
		../../../Qt/6.9.1/macos/libexec/moc
	/Users/amirmahdinaghsh/Qt/6.9.1/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=201402L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=17 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/amirmahdinaghsh/Qt/6.9.1/macos/mkspecs/macx-clang -I/Users/amirmahdinaghsh/Documents/GitHub/Bank_Operation -I/Users/amirmahdinaghsh/Qt/6.9.1/macos/lib/QtWidgets.framework/Headers -I/Users/amirmahdinaghsh/Qt/6.9.1/macos/lib/QtGui.framework/Headers -I/Users/amirmahdinaghsh/Qt/6.9.1/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/17/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/amirmahdinaghsh/Qt/6.9.1/macos/lib transferdialog.h -o moc_transferdialog.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_loginwindow.h ui_customerwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_loginwindow.h ui_customerwindow.h
ui_loginwindow.h: loginwindow.ui \
		../../../Qt/6.9.1/macos/libexec/uic
	/Users/amirmahdinaghsh/Qt/6.9.1/macos/libexec/uic loginwindow.ui -o ui_loginwindow.h

ui_customerwindow.h: customerwindow.ui \
		../../../Qt/6.9.1/macos/libexec/uic
	/Users/amirmahdinaghsh/Qt/6.9.1/macos/libexec/uic customerwindow.ui -o ui_customerwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main_qt.o: main_qt.cpp ../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qapplication.h \
		loginwindow.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qmessagebox.h \
		Customer.h \
		User.h \
		LinkedList.h \
		Admin.h \
		bankingsystem.h \
		Account.h \
		../../../Qt/6.9.1/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.1/macos/lib/QtCore.framework/Headers/qobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main_qt.o main_qt.cpp

bankingsystem.o: bankingsystem.cpp bankingsystem.h \
		LinkedList.h \
		Customer.h \
		User.h \
		Admin.h \
		Account.h \
		../../../Qt/6.9.1/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.1/macos/lib/QtCore.framework/Headers/qobject.h \
		SavingsAccount.h \
		CurrentAccount.h \
		LoanAccount.h \
		../../../Qt/6.9.1/macos/lib/QtCore.framework/Headers/QString \
		../../../Qt/6.9.1/macos/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/6.9.1/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.9.1/macos/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bankingsystem.o bankingsystem.cpp

loginwindow.o: loginwindow.cpp loginwindow.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qmessagebox.h \
		Customer.h \
		User.h \
		LinkedList.h \
		Admin.h \
		ui_loginwindow.h \
		customerwindow.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QListWidgetItem \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qlistwidget.h \
		adminwindow.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QGridLayout \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QLineEdit \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QTextEdit \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QTableWidget \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QTableWidgetItem \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QComboBox \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QGroupBox \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qgroupbox.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QTabWidget \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QInputDialog \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QHeaderView \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qheaderview.h \
		bankingsystem.h \
		Account.h \
		../../../Qt/6.9.1/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.1/macos/lib/QtCore.framework/Headers/qobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loginwindow.o loginwindow.cpp

customerwindow.o: customerwindow.cpp customerwindow.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QListWidgetItem \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qlistwidget.h \
		Customer.h \
		User.h \
		LinkedList.h \
		ui_customerwindow.h \
		transferdialog.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qdialog.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QGridLayout \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QComboBox \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QLineEdit \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qmessagebox.h \
		Account.h \
		bankingsystem.h \
		Admin.h \
		../../../Qt/6.9.1/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.1/macos/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QInputDialog \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../../Qt/6.9.1/macos/lib/QtCore.framework/Headers/QTextStream \
		../../../Qt/6.9.1/macos/lib/QtCore.framework/Headers/qtextstream.h \
		../../../Qt/6.9.1/macos/lib/QtCore.framework/Headers/QDateTime \
		../../../Qt/6.9.1/macos/lib/QtCore.framework/Headers/qdatetime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o customerwindow.o customerwindow.cpp

adminwindow.o: adminwindow.cpp adminwindow.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QGridLayout \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QLineEdit \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QTextEdit \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QTableWidget \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QTableWidgetItem \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QComboBox \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QGroupBox \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qgroupbox.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QTabWidget \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QInputDialog \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QHeaderView \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qheaderview.h \
		Admin.h \
		User.h \
		LinkedList.h \
		bankingsystem.h \
		Customer.h \
		Account.h \
		../../../Qt/6.9.1/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.1/macos/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adminwindow.o adminwindow.cpp

transferdialog.o: transferdialog.cpp transferdialog.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qdialog.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QGridLayout \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QComboBox \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QLineEdit \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qmessagebox.h \
		Customer.h \
		User.h \
		LinkedList.h \
		Account.h \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt/6.9.1/macos/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o transferdialog.o transferdialog.cpp

Account.o: Account.cpp Account.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Account.o Account.cpp

User.o: User.cpp User.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o User.o User.cpp

Customer.o: Customer.cpp Customer.h \
		User.h \
		LinkedList.h \
		Account.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Customer.o Customer.cpp

Admin.o: Admin.cpp Admin.h \
		User.h \
		LinkedList.h \
		Customer.h \
		SavingsAccount.h \
		Account.h \
		CurrentAccount.h \
		LoanAccount.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Admin.o Admin.cpp

SavingsAccount.o: SavingsAccount.cpp SavingsAccount.h \
		Account.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SavingsAccount.o SavingsAccount.cpp

CurrentAccount.o: CurrentAccount.cpp CurrentAccount.h \
		Account.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CurrentAccount.o CurrentAccount.cpp

LoanAccount.o: LoanAccount.cpp LoanAccount.h \
		Account.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LoanAccount.o LoanAccount.cpp

moc_bankingsystem.o: moc_bankingsystem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bankingsystem.o moc_bankingsystem.cpp

moc_loginwindow.o: moc_loginwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loginwindow.o moc_loginwindow.cpp

moc_customerwindow.o: moc_customerwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_customerwindow.o moc_customerwindow.cpp

moc_adminwindow.o: moc_adminwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_adminwindow.o moc_adminwindow.cpp

moc_transferdialog.o: moc_transferdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_transferdialog.o moc_transferdialog.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/BankingSystemGUI/bin || mkdir -p $(INSTALL_ROOT)/opt/BankingSystemGUI/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/BankingSystemGUI/bin/BankingSystemGUI.app
	
	$(QINSTALL) BankingSystemGUI.app $(INSTALL_ROOT)/opt/BankingSystemGUI/bin/BankingSystemGUI.app
	-$(STRIP) $(INSTALL_ROOT)/opt/BankingSystemGUI/bin/BankingSystemGUI.app/Contents/MacOS/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/BankingSystemGUI/bin/BankingSystemGUI.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/BankingSystemGUI/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

